### ISSUE TITLE
Please explain how this is better / different than other options

### ISSUE THREAD

**Issue by emchristiansen** [guari/eclipse-ui-theme#10]
It seems there are several options now for theming Eclipse.
For example, [eclipse-ui-themes](https://github.com/rogerdudler/eclipse-ui-themes) also enables a dark theme with Eclipse.
So, please explain in the README what sets this project apart.

**Comment by guari** [comment]
Hi @emchristiansen, currently this is a theme based on Eclipse pseudo-CSS capabilities. The theme you linked uses the same approach, but AFAIK that theme adds dark styles only for some main components, while this tries to customize every UI component that can be currently styled with the E4 CSS engine.
For the rest, which may be better than another is just a matter of a user's taste.

**Comment by emchristiansen** [comment]
Thanks for the reply.
Can you update the README with that info?
