### ISSUE TITLE
Preferences menu does not appear

### ISSUE THREAD

**Issue by trainto** [guari/eclipse-ui-theme#100]
I've installed MoonRise from eclipse market, and the installation went well without any error.
But I cannot find any menu for MoonRise in Preferences -> general -> appearance.

I only can see just 'Colors and Font', 'Label Decoration' just like the same as before MoonRise installation.

To figure out what went wrong, I tried Eclipse from terminal, but there is no message related to MoonRise plug-in.

Any ideas?

OS: Windows 7 64bit
Eclipse: 4.5.1 (Mars.1)
Java: 1.8

**Comment by trainto** [comment]
Sorry for false alarm!

I thought it makes independent menu for itself. I've found it has been integrated theme of default Appearance setting.

Sorry again.

**Comment by ricciozhang** [comment]
nothing serious
