### ISSUE TITLE
Support for 2019-12

### ISSUE THREAD

**Issue by mschleeweiss** [guari/eclipse-ui-theme#115]
When dragging and dropping the marketplace link into Eclipse I get the following error:

![image](https://user-images.githubusercontent.com/2648848/76634226-4c461980-6546-11ea-9a31-de77907ea0ce.png)

My Version:

Eclipse IDE for Java Developers

Version: 2019-12 (4.14.0)
Build id: 20191212-1212

OS: Windows 10

**Comment by PyvesB** [comment]
A fork of this plugin was merged back into the main Eclipse Platform code many years back. This theme has now effectively become the default Dark Eclipse theme. There is little point in adding 2019-12 support to this early days plugin. :wink:
