### ISSUE TITLE
Colors in search window

### ISSUE THREAD

**Issue by pacacc** [guari/eclipse-ui-theme#13]
![capture](https://f.cloud.github.com/assets/6003547/1594257/e2e1c7b4-52d7-11e3-9b4a-472fa37ae119.JPG)

(using eclipse kepler c/c++ edition, if makes any difference)

the colors in this window are completely unusable.
Tried to change them, but could not figure how.

It is possible to change this? (or at least the foreground color to gray-ish)

Also the colors used as "selected item" for  lists (seen in image as the selected_line) are very difficult to read. :(
(happens the same in project "Explorer Window" for the selected/highlighted line/item)

Apart from this, I'm loving your theme =D

**Comment by guari** [comment]
Hi, unfortunately only the foreground/background color for the whole list can be changed.
The background color of the selected line is hard-coded and depends on system theme colors, you can find the same color in Windows Explorer (the same goes eg. for folding arrows).
For the background/foreground colors found in some keyword results, try to look into Eclipse Preferences, probably there is a setting for them that currently, can be changed only from there...
AFAIK some of these settings found in Preferences should be editable directly in CSS starting from Eclipse 4.4 M4. ;)
