### ISSUE TITLE
package explorer and outline bar are not dark

### ISSUE THREAD

**Issue by vijayvd** [guari/eclipse-ui-theme#15]
Hi all,
I installed eclipse-ui-theme on my laptop (ubuntu 13.04) and desktop (ubuntu 12.04). On ubuntu 12.04 the theme is working very well but on ubuntu 13.04, the package explorer and outline bar are not dark.
![screenshot from 2013-12-07 20 17 28](https://f.cloud.github.com/assets/3750963/1699552/9962c97c-5fa6-11e3-8f7f-45959d1b60a9.png)

Is there a work around this?

Thanks,
Vijay

**Comment by collinpeters** [comment]
Try a dark gtk theme. AFAIK the list windows still take hints from the gtk theme. Let us know if you experience issue #11 after that.

**Comment by vijayvd** [comment]
I don't have any dark gtk theme. I am rolling back to the classic theme.

**Comment by ssmy** [comment]
I see this as well, unfortunately. Dark or light GTK theme. I've tried several. It _should_ work, but doesn't. Eclipse 4.2 or 4.3. Ubuntu 13.04. Any other ideas? In the meantime I just usually minimize the package explorer

**Comment by guari** [comment]
Probably you have to use another different system theme for now, I haven't looked its code but the new Ubuntu theme forces some settings for java application appearence. Styles for those widgets are defined in Moonrise stylesheet, you can check them with CSS Spy (bottom-right textbox reports the styles assigned to the selected widget). In some cases they are loaded but not applied by Eclipse engine. Substantially it's an Eclipse bug/failure, in those cases it can not be done almost anything at plugin level.
As a workaround you can try to load in Ubuntu 13.10 the default theme of Ubuntu 13.04.

**Comment by ssmy** [comment]
Well, I am using ubuntu 13.04. And it's the same with any gtk theme. Some things change, but not the package explorer, outline bar etc.

**Comment by guari** [comment]
Ubuntu 13.04, default theme, Moonrise 0.8.5 on Eclipse 4.3 (screenshot taken a while ago):

![screenshot](https://f.cloud.github.com/assets/3869503/1894970/8ab8e9aa-7b09-11e3-80d5-9cd46297e46b.png)

(but also any other theme I installed on my machine doesn't have bright Package Explorer or Outline, everything works as expected also when I boot in Gnome 3 / Gnome Shell instead of Unity)

**Comment by ssmy** [comment]
Hmm. Looks like my per-application gtkrc change wasn't applying to the white parts for some reason. Strange. Well, I got it looking correct by changing to match your settings. Thanks.
