### ISSUE TITLE
Java fonts are black on dark gray

### ISSUE THREAD

**Issue by arobinson** [guari/eclipse-ui-theme#18]
I tried using this on Kepler, but when I applied the appearance and restarted, the Java text was black on the dark gray background. Does not look like it is installing the correct colors for the editor, at least it is not working in a java editor.

**Comment by guari** [comment]
Have you tried to import into Eclipse the .epf file for syntax highlighting? 
(you can find the link in the README)

**Comment by arobinson** [comment]
I found other syntax highlighting themes out there for the editors. I misunderstood that this would change the UI as well as the code editor. Sorry about that

**Comment by guari** [comment]
ok, don't worry, UI and syntax highlighting have separate settings so you can use what you like or change it in Eclipse editors preferences ;)
