### ISSUE TITLE
Please make entry on Eclipse marketplace

### ISSUE THREAD

**Issue by paulvi** [guari/eclipse-ui-theme#21]
Please make entry on Eclipse marketplace

https://marketplace.eclipse.org/addcontent

**Comment by guari** [comment]
Updated README with marketplace entry ;)

**Comment by paulvi** [comment]
Then see what happens :)

**Comment by paulvi** [comment]
Yes, it made it to TOP15 http://marketplace.eclipse.org/content/eclipse-moonrise-ui-theme/metrics#.UvxOA7RxbMw ;-)

**Comment by paulvi** [comment]
@guari But the most interesting is that it is now going to be within Eclipse. Could you share how did it happen and the experience please.

**Comment by paulvi** [comment]
@guari Congratulation Moonrise is now TOP12 plugin http://marketplace.eclipse.org/metrics/successful_installs/last30days

**Comment by paulvi** [comment]
Dark theme is in Eclipse since M6 http://download.eclipse.org/eclipse/downloads/drops4/S-4.4M6-201403061200/news/

> A new experimental CSS theme based on a community contribution has been added. This popular community theme demonstrates the capabilities of the current CSS styling. This new theme helps the Platform team to continue to improve these capabilities.
> 
> CSS theming in Eclipse 4 does currently not allow to configure the syntax highlighting in text editors (e.g. the Java editor), so it is recommended to use the dark theme together with additional settings as for example provided by the Eclipse color theme project. 

Interesting is that Andrea Guarinoni is not mentioned, but anonymous community and Eclipse color theme project http://eclipsecolorthemes.org/

**Comment by guari** [comment]
yes, you're right, anyway I haven't made it for glory, I made it hoping it can be usefull in some ways... and it seems to be... :)
Moreover, the version in M6 has CSS bugs that this plugin has never had and Eclipse Color Theme is not the best choice for styling syntax highlighting for a dark theme, the .epf file provided here offers tons of settings that Eclipse Color Theme leaves empty ;)

**Comment by paulvi** [comment]
That was bold move of yours, great and nice.

But something was telling me and you confirmed just now, that dark theme shipped with Eclipse won't be the best (until something changes about all related projects)

But in effect now there is incompatible clone of your work, that is to be supported "by broader community", and at the same time you are (hopefully) to continue this work, with less exposure as it should be.

I believe in ideal world Eclipse should have mirror of this repository. Or vise versa this repository continues as Eclipse mirror.

**Comment by guari** [comment]
I will probably keep synced the two repositories for now, M7 should have the same changes that are already available with this plugin (I committed them to Eclipse few days ago), then let's see if some patches to CSS and SWT will be made, maybe I will try to commit some of them too, I just need some free time for looking the code.

**Comment by paulvi** [comment]
I see. It can be synced in both direction, the only difficulty is to find time.
