### ISSUE TITLE
Android XML files and Graphical Layout

### ISSUE THREAD

**Issue by Teleshot** [guari/eclipse-ui-theme#23]
![screenshot on 1 7 2014 at 2 42 40 pm](https://f.cloud.github.com/assets/489790/1859852/6e5ae374-77aa-11e3-92db-490ebeb3cc56.png)

![screenshot on 1 7 2014 at 2 46 47 pm](https://f.cloud.github.com/assets/489790/1859864/91f975d4-77aa-11e3-9e1c-e8a8c16472e2.png)

When working with Android XML files the Graphical Layout and XML file tabs seem to get covered by the Palette options but they are still selectable.

 I am on Windows 7 and I have tried both the standalone version and the Eclipse 4 Chrome Theme version but both have the same problem.

**Comment by guari** [comment]
This seems an unexpected behavior, on my Win7 (Kepler) the bottom tabs are ok:

![image](https://f.cloud.github.com/assets/3869503/1860333/02a81626-77b2-11e3-899c-daea640b05b7.jpg)

(there is still a bug when hovering the items on the left but, as far as I known, is an Eclipse/SWT implementation lack in which are hard-coded the colors of CLabel control for the hover state)

**Comment by jacobdeichert** [comment]
I have the same issue. I'm using Windows 8.1, Eclipse 4.2.1

![issue](https://f.cloud.github.com/assets/1631044/2152417/e4ae40d6-9418-11e3-8777-cb043a2fcd1f.png)

**Comment by guari** [comment]
As far as I know, currently there is no way to load different stylesheets for different Windows versions, as a quick workaround you can force the old renderer for tabs by copy-pasting these lines at the end of the two moonrise css for WIN (`moonrise-ui-standalone_WIN.css` and `moonrise-ui_WIN.css`):

``` css
    CTabFolder[style~='SWT.DOWN'][style~='SWT.BOTTOM'] {
        swt-tab-renderer: null;
        swt-simple: true;   
    }
```

**Comment by guari** [comment]
Try also if this issue is still present with the last Eclipse release.

**Comment by jacobdeichert** [comment]
@guari thanks for that css fix. It worked. That was the only issue bugging me a little.

**Comment by jacobdeichert** [comment]
Looks much better, thanks for fixing this!
