### ISSUE TITLE
marketplace-tabs and system-dialogs are not readable

### ISSUE THREAD

**Issue by mxub** [guari/eclipse-ui-theme#25]
So if I go to the MarketPlace or I get system dialog I can't read the options ..

does anyone know where this preference is ?

![notreadable](https://f.cloud.github.com/assets/570654/1868556/f27b9500-786c-11e3-86b7-fa875efa7c53.jpg)

**Comment by guari** [comment]
It is contained into `moonrise-ui_[OSX-patch].css`, it's the `Combo` widget color
(due to an Eclipse bug, you need to copy-paste the content of the file into the other moonrise stylesheets for OSX).

Anyway, it happens only for the `Combo` widget in marketplace? other `Combo` tabs are ok?

**Comment by mxub** [comment]
some button are okay some not .. so what I also find is:

![notreadable2](https://f.cloud.github.com/assets/570654/1869886/f8070dac-787f-11e3-8afb-638c76c268f8.jpg)

**Comment by guari** [comment]
Ok, tabs in marketplace for OSX will be fixed in next version.
For dialog buttons, I need to know at least the action to show those dialogs since they are usually ok for common dialogs ;)

**Comment by mxub** [comment]
so I deleted a Class - and I got a dialog with those invisible buttons. maybe that helps.

**Comment by josephknight** [comment]
Tried the CSS copy-over work-around to no success. Really looking forward to this fix. Love being able to work in Eclipse without being blasted with white backgrounds; unfortunately this theme is not useable for us mac users when the buttons are completely illegible until clicked upon.
