### ISSUE TITLE
lock window issue

### ISSUE THREAD

**Issue by yayaigo2010** [guari/eclipse-ui-theme#27]
I install other color theme plugin first,
then I install moonrise,restart eclipse, it will lock eclipse window,the mouse event have no response 
Maybe moonrise have confilict with color theme ,and cause endless loop
How to fix the issue?

**Comment by guari** [comment]
mmm.. I never experienced this, it should be a bug in Color Theme Plugin because (for now) Moonrise plugin is pure CSS (it can't slow down or hang the IDE unless the other components or the IDE itself have some issues)

What platform/OS are you using?

**Comment by yayaigo2010** [comment]
Mac OS 10.9 ,Eclipse version:4.2

**Comment by yayaigo2010** [comment]
finally I fix that , and then moonrise is working. I modify eclipse.ini to set max memory. thanks . This plugin save my eye

**Comment by guari** [comment]
Great! Thanks for the update.
