### ISSUE TITLE
[build] "Unable to satisfy dependency from com.github.eclipseuitheme.themes.feature.feature.group 0.8.5 to com.github.eclipseuitheme.themes.moonrise-ui [0.8.5,0.8.6)."

### ISSUE THREAD

**Issue by paulvi** [guari/eclipse-ui-theme#29]
```
[INFO] Cannot complete the request.  Generating details.
[INFO] Cannot complete the request.  Generating details.
[INFO] {osgi.ws=win32, osgi.os=win32, osgi.arch=x86_64, org.eclipse.update.install.features=true}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.github.eclipseuitheme.themes.feature.feature.group 0.8.5
[ERROR]   Missing requirement: com.github.eclipseuitheme.themes.feature.feature.group 0.8.5 requires 'com.github.eclipseuitheme.themes.moonrise-ui [0.8.5,0.8.6)' but it could not be found
[ERROR]
[ERROR] Internal error: java.lang.RuntimeException: "No solution found because the problem is unsatisfiable.": ["Unable to satisfy dependency from com.github.eclipseuitheme.themes.feature.feature.group 0.8.5 to com.github.eclipseuitheme.themes.moonrise-ui [0.8.5,0.8.6).", "No solution found because the problem is unsatisfiable."] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: "No solution found because the problem is unsatisfiable.": ["Unable to satisfy dependency from com.github.eclipseui
theme.themes.feature.feature.group 0.8.5 to com.github.eclipseuitheme.themes.moonrise-ui [0.8.5,0.8.6).", "No solution found because the problem is unsatisfiable."]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
```

**Comment by paulvi** [comment]
OK the above error was because version in pom.xml was not updated after MANIFEST.MF

but now there is ERROR below (I wonder was it before)

> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.19.0:validate-id (default-validate-id) on project com.github.eclipseuitheme.themes.plugin: The Maven artifactId (currently: "c
> om.github.eclipseuitheme.themes.plugin") must be the same as the bundle symbolic name (currently: "com.github.eclipseuitheme.themes.moonrise-ui") -> [Help 1]

**Comment by paulvi** [comment]
that fixed with adding `.qualifier` to plugin and feature version.

> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:0.19.0:assemble-repository (default-assemble-repository) on project com.github.eclipseuitheme.themes.updatesite: No content
> specified for p2 repository -> [Help 1]

That was only solved by renaming `site.xml` to `category.xml`. That may disrupt your previous manual build.
And for that I don't know clue, because as I know `site.xml` is deprecated in newer Tycho version.
Also result arrives in `com.github.eclipseuitheme.themes.updatesite\target\repository`, not in  `com.github.eclipseuitheme.themes.updatesite`

Could you please describe manual build steps.

**Comment by guari** [comment]
I used Eclipse own build system. 
Open site.xml with the Eclipse viewer (not as text editor), then press 'Build  All' button to generate in one step all the needed archives for the update site (http://wiki.eclipse.org/FAQ_How_do_I_create_an_update_site_(site.xml)%3F)

**Comment by paulvi** [comment]
OK then `site.xml` can stay at the place for manual builds. I will update PR tomorrow or do it yourself if you know.

Anyway use `mvn -Dtycho.mode=maven org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=0.10.0-SNAPSHOT` to update version or don't forget to update versions in pom.xml as well.

Please ask questions, there should be some discussion.

**Comment by guari** [comment]
ok, thanks Paul, I wrote pom.xml files by hand for future usages, I never used Maven\Tycho to build. 
I read your commits now, they seem pretty clear, my only concern is if it might break the update site for current users. Is there a way to build the archives with Maven by keeping the current folder structure for the update site (so it's also possible to build the package both manually and automatically if needed)?

**Comment by paulvi** [comment]
maven/tycho is fully additional, supportive. You can continue build with 'Build All' button (just update versions everywhere, see above). Also to to keep `site.xml` and `categories.xml` the same (if maven build for p2 repository is needed)

As long as `.jar` files are at old place, users will get them as usual.
