### ISSUE TITLE
Folding option in C editor

### ISSUE THREAD

**Issue by noamelf** [guari/eclipse-ui-theme#3]
Hi,
Great job with the theme !
The folding line in C editor dosent match the theme (in python it does...)
Is there is a way to fix this?

![image](https://f.cloud.github.com/assets/4347848/921488/51c9f6ba-fefa-11e2-8ea8-07ffc60369e4.png)

**Comment by guari** [comment]
It seems a bug in how Eclipse handles that CDT's style since the nodes structure is the same as other languages perspective. I uploaded a new version with a workaround.

**Comment by noamelf** [comment]
Thanks mate !
בתאריך 8 באוג 2013 13:27, מאת "guari" notifications@github.com:

**Comment by arichiardi** [comment]
Sorry to barge in, we are having some issue [here](https://github.com/laurentpetit/ccw/issues/799) as well, any advice?
