### ISSUE TITLE
Some backgrounds are white on linux

### ISSUE THREAD

**Issue by kotoroshinoto** [guari/eclipse-ui-theme#36]
![all_white](https://f.cloud.github.com/assets/1337560/2117220/0e0b4252-90be-11e3-9930-09b814af8ce6.png)
fedora 20
mate desktop
downloaded eclipse from the website (did not use yum repo version).

the package explorer background and preferences category selection backgrounds remain white after applying the theme. Makes the grey text nearly impossible to read.

Can be adjusted by choosing a dark OS UI theme, but if possible to override this some other way, this should not be required.

**Comment by guari** [comment]
It's an issue of your system theme that forces the colors for the Tree widget of Java applications. You need to switch to another OS theme (not necessarily a dark one) or edit its .gtkrc file.
