### ISSUE TITLE
Ubuntu 13.10 Gnome 3 button labels invisible

### ISSUE THREAD

**Issue by matejuh** [guari/eclipse-ui-theme#37]
The button labels are invisible. I tried to change system theme, but it doesn't help.

![screenshot from 2014-02-09 19 21 23](https://f.cloud.github.com/assets/1061307/2120496/63fa9ad8-91b7-11e3-8514-ce1e0cc253c0.png)

**Comment by guari** [comment]
For a quick fix with current plugin version (0.8.7), you need to copy-paste [those](https://github.com/guari/eclipse-ui-theme/blob/master/com.github.eclipseuitheme.themes.plugin/themes/css/moonrise-ui_%5BOSX-patch%5D.css#L33L99) lines at the end of the two css files for GTK into moonrise package (`moonrise-ui_GTK.css` and `moonrise-ui-standalone_GTK.css`).

On my GNOME 3 installation, button background works, however I don't know if Eclipse is able to distinguish a GTK version from another...

**Comment by matejuh** [comment]
Thanks for quick response. It's working. I like this theme, great work!
