### ISSUE TITLE
No Moonrise Listed under Window > Preferences > General > Appearance

### ISSUE THREAD

**Issue by steelow** [guari/eclipse-ui-theme#38]
Hello,

I like the Moonrise screenshot on your landing page. So I installed the theme, restarted Eclipse and went to Window > Preferences > General > Appearance;
The Moonrise was not in the list.

By the way, I am using Eclipse Kepler. I have gone back to the Eclipse Color Theme, but would still like to switch to Moonrise if possible.

Do you have any ideas what might be causing this?

Thanks,

Steve

**Comment by guari** [comment]
Hi, which OS and installation method are you using?

To find the cause you can try to start Eclipse from a terminal/prompt so if Moonrise plugin is correctly installed you should see some error messages printed there when the IDE tries to load it.

**Comment by steelow** [comment]
Hi Guari,

I am using Windows XP. If I do go the route of starting eclipse from the command line, would I be required to create a bat file in order to successfully do so?

Thanks

**Comment by guari** [comment]
Probably no, just open a command-prompt and enter something like:
`"C:\Program Files\Eclipse\Kepler 4.3\eclipse.exe" -consoleLog`
to start your Eclipse executable.
This should be enough. 

(you can also try with `-debug` flag)

**Comment by steelow** [comment]
I ran the -consoleLog command and the IDE started up with no message regarding the moonrise theme. The only message I received was something about eGit .  I listed them below under the 'Log messages' section. I am not using Git though. Is it a requirement for using your theme?

Although, I do see the moonrise plugin file com.github.eclipseuitheme.themes.moonrise-ui_0.8.7.201402091948 in the plugins folder. Even when I revisit to the Eclipse Market place to uninstall it - the 'uninstall' button does not appear under it like it does for other installed items.

Log messages:
!Entry org.eclipse.egit.ui 2 0 2014-02-11 0:51:59.492
!MESSAGE Warning: EGit can't respect system level Git settings which might be configured in $(gitPrefix)/etc/gitconfig under the native Git installation directory...

!Entry org.eclipse.egit.ui 2 0 2014-02-11 0:51:59.529
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git user global configuration and to define the default location to store the repositories... 

Thanks

Steve

On Monday, February 10, 2014 4:42 PM, guari notifications@github.com wrote:

Probably no, just open a command-prompt and enter something like:
"C:\Program Files\Eclipse\Kepler 4.3\eclipse.exe" -consoleLog
to start your Eclipse executable.
This should be enough. 
(you can also try with -debug flag)

**Comment by guari** [comment]
EGit is not required, probably that is an Eclipse internal warning, I see it too.
Maybe there is something unexpected in the compression of the jar archives I uploaded, related also to #39...

I rebuild and reupload the packages, try to uninstall/delete the plugin from your Eclipse folder then install the new build from the updatesite/marketplace, let me know if the issue is solved..

**Comment by steelow** [comment]
Thanks Guari. I will try it this evening and let you know how it goes. 

Thanks again.

Steve

**Comment by n3p** [comment]
Window/Preferences/ - expand General, click Appearance, click the Theme: dropdown menu and select Moonrise. Hope that helps
