### ISSUE TITLE
Can't add update site.

### ISSUE THREAD

**Issue by akwala** [guari/eclipse-ui-theme#42]
No repository found at https://raw.github.com/guari/eclipse-ui-theme/master/com.github.eclipseuitheme.themes.updatesite.

**Comment by guari** [comment]
Update site is working for me, try to use the marketplace link if you have issues.
Both the update-site and marketplace installations are sharing the same repository on github.

**Comment by akwala** [comment]
Works now, thanks. (I did try both, via the marketplace and adding the link manually.)
