### ISSUE TITLE
Jeeeyul's Eclipse Themes 2.0 will be released soon.

### ISSUE THREAD

**Issue by jeeeyul** [guari/eclipse-ui-theme#49]
Hello @guari 

Jeeeyul's Eclipse Themes(Formerly "Chrome") is about to release 2.0 soon.
What if your theme has any dependency for 1.X, it is not compatible anymore.

2.0 is totally re-written and it supports third party extensions officially now.
Tons of new [CSS](https://github.com/jeeeyul/eclipse-themes/wiki/CSS)  properties are provided. [Deploy your preset](https://github.com/jeeeyul/eclipse-themes/wiki/Deploy-your-preset) document may be helpful also. You can also just use new CTabFolderRenderer and that are documented on [CSS](https://github.com/jeeeyul/eclipse-themes/wiki/CSS).

Currently You can test 2.0 beta version with `http://eclipse.jeeeyul.net/beta-update`

What if you have any questions or request, let me know.

Cheers!

**Comment by paulvi** [comment]
@guari has not updated this repo for 3 weeks, though before he was very active.
I took a look at [eclipse repo](https://github.com/eclipse/eclipse.platform.ui) (mentioned in README)

At https://github.com/eclipse/eclipse.platform.ui/tree/master/bundles/org.eclipse.ui.themes you can see that this repo was merged into Eclipse and seems to be active.

From [Bug 416218 - [CSS] Contribute dark theme to Eclipse ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=416218)

> Andrea Guarinoni CLA 2013-10-07 11:55:31 EDT
> Hi, as said to Lars, you can use it as you like if it might be of some help.

[Bug 427138 - Integrate dark theme into Eclipse SDK product ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=427138)

@guari is this the end of this repo development?

**Comment by guari** [comment]
Hi @jeeeyul, thanks for the update, your work is amazing! 
I will update Moonrise plugin with your new API soon.
The customization for hovered tabs and others settings you introduced will be useful for dark themes.

@PaulVI I can keep this repo updated, currently @jeeeyul's plugin is supported only here and it provides a better look at least for tabs.

**Comment by paulvi** [comment]
Hurray! I am glad to hear.

**Comment by paulvi** [comment]
@guari Do you use updated APIs from @jeeeyul now?

**Comment by guari** [comment]
yes ;)

**Comment by paulvi** [comment]
could have been 0.9.0 then...
