### ISSUE TITLE
Question - Panels padding

### ISSUE THREAD

**Issue by HubertTatar** [guari/eclipse-ui-theme#58]
How can one change padding between panels ? I found it is too big on laptop screen. I've previously used Dark Juno which don't have so much space between panels. I've tried to configure this via css of Moonrise but i failed.
![untitled](https://cloud.githubusercontent.com/assets/1004725/2704351/16e46724-c46b-11e3-9f4e-2e4047a0ba01.png)

**Comment by guari** [comment]
It's a bit tricky, for Moonrise Standalone stylesheets try to remove the Part's shadows (that add an hard-coded margin):

```
.MPartStack {
    swt-shadow-visible: false;
}
```

for Moonrise stylesheets that use Jeeeyul's tab renderer instead change the value of:

```
.MPartSashContainer {
    jsash-width: 4px;  /* Gap between each parts */
}
```

**Comment by HubertTatar** [comment]
Thanks for info.
