### ISSUE TITLE
Rows in Package Explorer switch back to white

### ISSUE THREAD

**Issue by krisdabi** [guari/eclipse-ui-theme#62]
This happens if the project is attached to a Git repo.  Uncommitted files & ignored folders don't follow the dark theme.

![screen shot 2014-05-07 at 2 38 07 pm](https://cloud.githubusercontent.com/assets/1390647/2909213/5ad311a2-d630-11e3-92f6-55f4922a0398.png)

**Comment by guari** [comment]
Hi Kris, it's your default preferences, see [syntax-highlighting](https://github.com/guari/eclipse-ui-theme#syntax-highlighting-scheme-optional)

Import the provided .epf file ;)

**Comment by krisdabi** [comment]
The last screenshot was using Eclipse Color Theme Plugin + RainbowDrops.xml.

After importing RainbowDrops.epf, some lines in Package Explorer & Outline have a darker line.  I still see white backgrounds for folders & files that Git ignores.  (see: gen & bin folders)

![screen shot 2014-05-09 at 2 27 53 pm](https://cloud.githubusercontent.com/assets/1390647/2933605/f250f440-d7c0-11e3-940e-a13692e3e96f.png)

**Comment by guari** [comment]
Updated, thanks for report

Importing again the .epf file should fix it.

**Comment by fengjiansunren** [comment]
I  don't  no  how  to do------------------ 原始邮件 ------------------
发件人: "guari"notifications@github.com
发送时间: 2014年5月10日(星期六) 晚上11:58
收件人: "guari/eclipse-ui-theme"eclipse-ui-theme@noreply.github.com;
主题: Re: [eclipse-ui-theme] Rows in Package Explorer switch back to white(#62)

Updated, thanks for report

&mdash;
