### ISSUE TITLE
File Navigator is too dark toi see filenames.

### ISSUE THREAD

**Issue by intotecho** [guari/eclipse-ui-theme#63]
I have moonrise installed, but I have a question.
My filenames and the little down arrows on the left of the file names are very dark. 
It is hard to see. 
I have searched the docs but can't find how to change this setting.
![image](https://cloud.githubusercontent.com/assets/659672/3117435/d92cf0ba-e72c-11e3-9f75-a5f2cea015f2.png)

**Comment by guari** [comment]
Try to import the .epf file, it's probably eGit settings ;)

**Comment by intotecho** [comment]
Thanks, 
The eGit color settings fixed the filename colors. 
I am still stuck on the caret and down arrow. It is cyan when I hover over it but invisible otherwise. There does not seem to be any configuration for it.

**Comment by guari** [comment]
See issue #1 and #26

**Comment by guari** [comment]
Duplicate of #1

**Comment by renderdan** [comment]
Can also set this via :
Windows > Preferences > General > Appearance > Colors and Fonts > Git > Uncommitted change (Foreground) > Edit

**Comment by iashkan** [comment]
Great thank you.

**Comment by wolf99** [comment]
This can also be a problem for files that are ignored by a .gitignore.

To remedy, change:  Windows > Preferences > General > Appearance > Colors and Fonts > Git > Ignored Resource (Foreground)
