### ISSUE TITLE
Update site not working

### ISSUE THREAD

**Issue by rantoniuk** [guari/eclipse-ui-theme#64]
https://raw.github.com/guari/eclipse-ui-theme/master/com.github.eclipseuitheme.themes.updatesite
shows Not Found, eclipse says no update site found :(

**Comment by guari** [comment]
Hi @warden, the update site is working, it points to the related folder on this repo.
In that folder there are no html files so if you try to open that link with a browser is normal that no webpage are displayed.

If you have issues, try to use the marketplace entry to install, the marketplace loads the data from the same update site on this repo ;)

**Comment by rantoniuk** [comment]
I did not try to open it in browser :)
For me, Eclipse Kepler says "no update site found", installing via marketplace has the same effect.
Installing manually from a ZIP (jar) file worked fine.

**Comment by guari** [comment]
Tested now on Kepler / Windows 7 and it works with no issues on my pc, both the marketplace and direct update-site. Check your firewall and your Eclipse platform bundle.

By the way, can you attach a screenshot with the error reported by the Eclipse Marketplace?
