### ISSUE TITLE
Is it alright if I submit a port to Intellij IDEA's Themes?

### ISSUE THREAD

**Issue by thomasnield** [guari/eclipse-ui-theme#97]
Hi Guari, 

I've been trying to find a way to contact you. I loved the Moonrise theme so much I ported it over best I could to Intellij IDEA. Would it be alright if I submit it to the IDEA themes website? 

http://www.ideacolorthemes.org/

**Comment by paulvi** [comment]
@guari who is Andrea Guarinoni (see http://marketplace.eclipse.org/content/eclipse-moonrise-ui-theme) rarely looks in here after donating the whole solution to Eclipse as Dark theme.  

Personally I would second. Going literally there is https://github.com/guari/eclipse-ui-theme/blob/master/COPYING file that is Eclipse license, I don't really know who would it apply for such case.

**Comment by thomasnield** [comment]
Thanks paulvi, I'll make some inquiries later.

**Comment by thomasnield** [comment]
I talked to Eclipse Licensing and Mike Milinkovich himself replied. He said it should be no problem as long as I published it under the EPL. However, ideacolorthemes.org uses some different license. I told Mike and he said it would clash with the EPL, or take enormous effort to re-license. So I independently distributed it under the EPL here https://github.com/thomasnield/idea_eclipse_dark_theme
